# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

wine_biz_data = [
  {name: 'Charles Smith Wine Jet City', location: '1136 S Albro Pl, Seattle, WA 98108', theme: 0, google_place_id: 'ChIJVym2i-xBkFQRX1O30QaiGIM'},
  {name: 'Elsom Cellars', location: '2960 4th Ave S, Seattle, WA 98134', average_rating: 5.0, theme: 0, google_place_id: 'ChIJb8KVi8kNkFQR_e7zWgSAneM'},
  {name: 'Stomani Cellars', location: '1403 Dexter Ave N, Seattle, WA 98109', average_rating: 2.0, theme: 0, google_place_id:'ChIJ4xKG6T0VkFQR-sIc8E4f_dQ'},
  {name: 'Hand Of God Wines', location: '308 9th Ave N, Seattle, WA 98109', average_rating: 4.0, theme: 0, google_place_id: 'ChIJrceiwjcVkFQRgLvQSohGx7o'},
  {name: 'The Tasting Room', location: 'Pike Place Market, 1924 Post Alley, Seattle, WA 98101', average_rating: 3.0, theme: 0, google_place_id: 'ChIJQVHlzbJqkFQR3KSsOoYgmr4'},
  {name: '21 Acres', location: '13701 NE 171st Street, Woodinville, WA 98072', average_rating: 5.0, theme: 0, google_place_id: 'ChIJ34iHbywMkFQR0H2syINxKt8'},
  {name: 'Adams Bench Winery', location: '14360 160th Pl NE, Woodinville, WA 98072', average_rating: 3.0, theme: 0, google_place_id: 'ChIJQyPIAlEMkFQRvzrV1hVs7LE'},
  {name: 'Alexandria Nicole Cellars', location: '14810 NE 145th St, Woodinville, WA 98072', average_rating: 4.0, theme: 0, google_place_id: 'ChIJicuRUrMNkFQRMDo0eD9XM1w'},
  {name: 'áMaurice Cellars', location: '14463 Woodinville-Redmond Rd NE, Woodinville, WA 98072', average_rating: 2.0, theme: 0, google_place_id: 'ChIJh_NZtYYSkFQRKVXSoEwzRCk'},
  {name: 'Laurelhurst Cellars Winery', location: '5608 7th Ave S, Seattle, WA 98108', theme: 0, google_place_id: 'ChIJa_hkM8BBkFQR0hRYEcdzLRA'},
  {name: 'Viscon Cellars', location: '5910 California Ave SW, Seattle, WA 98136', theme: 0, google_place_id: 'ChIJTWum_RxBkFQRR1PrcLQfdok'},
  {name: 'J Bookwalter Tasting Studio', location: '14810 NE 145th St, Woodinville, WA 98072', theme: 0, google_place_id: 'ChIJU9O3MlAMkFQRx7gm0DLgcn4'},
  {name: 'Rolling Bay Winery', location: '10334 Beach Crest, Bainbridge Island, WA 98110', theme: 0, google_place_id: 'ChIJJ2QHwzE8kFQRiIzbeC3eFxY'},
  {name: 'Fletcher Bay Winery', location: '9415 Coppertop Loop NE, Bainbridge Island, WA 98110', theme: 0, google_place_id: 'ChIJpzYKZyI8kFQRhGGlnMu4lrk'},
  {name: 'Eleven Winery', location: '287 Winslow Way E, Bainbridge Island, WA 98110', theme: 0, google_place_id: 'ChIJQ38_arc-kFQRV6RHlZ_N1eI'},
  {name: 'Island Vintners', location: '450 Winslow Way E, Bainbridge Island, WA 98110', theme: 0, google_place_id: 'ChIJ4Unf2bk-kFQREAw2KJPUW7Q'},
  {name: 'Aspenwood Cellars Winery', location: '18642 142nd Ave NE, Woodinville, WA 98072', theme: 0, google_place_id: 'ChIJT8htJJwOkFQRxRtnkFpEPY4'},
  {name: 'Waving Tree Winery', location: '11901 124th AVE NE, Kirkland, WA 98034', theme: 0, google_place_id: 'ChIJk9ongX8NkFQRBGUnuyk4yD4'},
  {name: 'Matthews Winery', location: '16116 140th Pl NE, Woodinville, WA 98072', theme: 0, google_place_id: 'ChIJQ_1q9jMMkFQRuH1vrYJZTpI'},
  {name: 'Eye of the Needle Winery', location: '19501 144th Ave NE, Woodinville, WA 98072', theme: 0, google_place_id: 'ChIJv2XfnqIOkFQRtEL1yxk5xdk'},
  {name: 'Northwest Cellars', location: '11909 124th Ave NE, Kirkland, WA 98034', theme: 0, google_place_id: 'ChIJ2-N2gH8NkFQRRrcIuMtQt_I'},
  {name: 'Eagle Harbor Wine Company', location: '278 Winslow Way E, Bainbridge Island, WA 98110', theme: 0, google_place_id: 'ChIJx1hwarc-kFQRwsrcUAOFVEY'},
  {name: 'Patterson Cellars', location: '14505 148th Ave NE, Woodinville, WA 98072', theme: 0, google_place_id: 'ChIJvRvgnqIOkFQR_DD-FUKD-Ug'},
  {name: 'Perennial Vintners', location: '8840 NE Lovgreen Rd, Bainbridge Island, WA 98110', theme: 0, google_place_id: 'ChIJrUIVMlI8kFQRzUC3AK7UAtU'},
  {name: 'Mark Ryan Winery', location: '14475 Woodinville-redmond Rd NE, Woodinville, WA 98072', theme: 0, google_place_id: 'ChIJObYJHJgOkFQRAPPNexih3zY'},
  {name: 'Martedi Winery', location: '16110 Woodinville-Redmond Rd NE, Woodinville, WA 98072', theme: 0, google_place_id: 'ChIJhR08f9INkFQRY0ZvozKCTkk'},
  {name: 'Darby Winery', location: '14450 Woodinville Redmond Rd NE, Woodinville, WA 98072', theme: 0, google_place_id: 'ChIJFTzqMLMNkFQRHPuP_t8ZIyg'},
  {name: 'Sparkman Cellars', location: '19501 144 Ave. NE, Woodinville, WA 98072', theme: 0, google_place_id: 'ChIJvRvgnqIOkFQRn_n95nhP7P8'},
  {name: 'Palouse Winery', location: '12431 Vashon Hwy SW, Vashon, WA 98070', theme: 0, google_place_id: 'ChIJv56L2HFGkFQRLutDnEVX5oM'},
  {name: 'Arista Wine Cellars', location: '320 5th Ave S, Edmonds, WA 98020', theme: 0, google_place_id: 'ChIJY6uJB_oakFQRqJfD0fic-38'},
  {name: 'Efeste', location: '19730 144th Ave NE, Woodinville, WA 98072', theme: 0, google_place_id: 'ChIJhcUW07wOkFQRxbqvJK16Ckg'},
  {name: 'Vashon Winery', location: '10317 SW 156th St, Vashon, WA 98070', theme: 0, google_place_id: 'ChIJXRsQcPJFkFQR6RpJJePkuyE'},
  {name: 'Finn Hill Winery', location: '8218 NE 115th Way, Kirkland, WA 98034', theme: 0, google_place_id: 'ChIJDXHLB0USkFQRJ4bNFkIwW_8'},
  {name: 'Almquist Family Vintners', location: '198 Nickerson St, Seattle, WA 98109', theme: 0, google_place_id: 'ChIJmbwqTwYVkFQROKjnZ0HRZk8'},
  {name: 'Barrique', location: '1762 Airport Way S, Seattle, WA 98134', theme: 0, google_place_id: 'ChIJTcHABJtqkFQRV13PMztNl8g'},
  {name: 'Bartholomew Winery', location: '3100 Airport Way S, Seattle, WA 98134', theme: 0, google_place_id: 'ChIJg8_PzIFqkFQRWpIerh8Xgu8'},
  {name: 'Cloudlift Cellars', location: '312 S Lucile St, Seattle, WA 98108', theme: 0, google_place_id: 'ChIJIQyGqMBBkFQRSERQywlWvcA'},
  {name: 'Eight Bells Winery', location: '6213-B Roosevelt Way NE, Seattle, WA 98115', theme: 0, google_place_id: 'ChIJz0ocfm8UkFQRR6e_meDMDvE'},
  {name: 'Falling Rain Cellars', location: '825 NW 49th Street, Seattle, WA 98107', theme: 0, google_place_id: 'ChIJH9cYpLYVkFQRRcfc1JXQMrs'},
  {name: 'Kerloo Cellars', location: '3911 1st Ave South, Seattle, WA 98134', theme: 0, google_place_id: 'ChIJn9yTHc1BkFQRHR6BePQfBBs'},
  {name: 'Nota Bene Cellars', location: '9320 15th Ave S Unit CC, Seattle, WA 98108', theme: 0, google_place_id: 'ChIJJxirmDFCkFQRZz7Mo9zkyZc'},
  {name: 'O·S Winery', location: '5319 4th Avenue South, Seattle, WA 98108', theme: 0, google_place_id: 'ChIJd81w1DFCkFQRfvWywekjcOw'},
  {name: 'Robert Ramsay Cellars', location: '1629 Queen Anne Ave N 102, Seattle, WA 98109', theme: 0, google_place_id: 'ChIJT3FvSxMVkFQRtcxKKRVeR70'},
  {name: 'Structure Cellars', location: '3849 1st Ave So suite D , Seattle, WA 98134', theme: 0, google_place_id: 'ChIJr4Yd2cxBkFQRZ3fgNqX11Ho'},
  {name: 'The Estates Wine Room', location: '307 Occidental Ave S, Seattle, WA 98104', theme: 0, google_place_id: 'ChIJoz8d16RqkFQRjlWaQ7mhmsA'},
  {name: 'Two Brothers Winery', location: '3902 California Ave SW, Seattle, WA 98116', theme: 0, google_place_id: 'ChIJM-wktFhAkFQRr1iFrgoZk-s'},
  {name: 'Ward Johnson Winery', location: '1445 Elliott Ave W, Seattle, WA 98119', theme: 0, google_place_id: 'ChIJldswcmUVkFQRTaUuCxpHRb8'},
  {name: 'Welcome Road Winery', location: '4415 SW Stevens St, Seattle, WA 98116', theme: 0, google_place_id: 'ChIJZYUT1WBAkFQRv44xhmc8xUw'},
  {name: 'Capri Cellars', location: '88 Front St S, Issaquah, WA 98027', theme: 0, google_place_id: 'ChIJidvxLYBlkFQR5vaX0vtNPek'},
  {name: 'Fivash Cellars', location: '602 234th Ave SE, Sammamish, WA 98074', theme: 0, google_place_id: 'ChIJXUJ_5OtxkFQRWya_GEvO8r8'},
  {name: 'Piccola Cellars', location: '112 W 2nd St, North Bend, WA 98045', theme: 0, google_place_id: 'ChIJ1-YDRCN8kFQRnIW6Ey1Etm4'}
]

coffee_biz_data = [
  {name: 'Slate Coffee Roasters', location: '602 2nd Ave, Seattle, WA 98104', theme: 3, google_place_id: 'ChIJwTxsg7pqkFQRiZGAJuyQsic'},
  {name: 'Elm Coffee Roasters', location: '240 2nd Ave S #103, Seattle, WA, 98104', theme: 3, google_place_id: 'ChIJv4Ih4LpqkFQRsEFZjeKx2tY'},
  {name: 'Victrola Coffee Roasters', location: '310 E Pike St, Seattle, WA, 98122', theme: 3, google_place_id: 'ChIJ7bdU9rJqkFQRqx0_701azUU'},
  {name: 'Lighthouse Roasters', location: '400 N 43rd St, Seattle, WA, 98103', theme: 3, google_place_id: 'ChIJwd-h4qwVkFQRgqm5OODEBQw'},
  {name: 'Caffe Lusso Coffee Roasters', location: '17725 NE 65th St A150, Redmond, WA 98052', theme: 3, google_place_id: 'ChIJC3sAKZZykFQRdhD7Ih63JUs'},
  {name: 'Caffe Luca Coffee Roasters', location: '885 Industry Dr, Seattle, WA 98188', theme: 3, google_place_id: 'ChIJ1Ybe7NtckFQRKs-T1RRb4Nc'},
  {name: 'Middle Fork Roasters', location: '420 S 96th St #6, Seattle, WA 98108', theme: 3, google_place_id: 'ChIJq7AmXtJDkFQRas-tiJQ-ZGE'},
  {name: 'Storyville Coffee Roasting Studio Coffee Shop & Tasting Room', location: '9459 Coppertop Loop NE, Bainbridge Island, WA 98110', theme: 3, google_place_id: 'ChIJvb1KRyI8kFQRwEFn3pThCRE'},
  {name: 'Fonte Coffee Roaster', location: '5501 6th Ave S, Seattle, WA 98108', theme: 3, google_place_id: 'ChIJVY1_5MBBkFQRCrD67CC2A0Y'},
  {name: 'Zoka Coffee Roasters and Tea Company', location: '129 Central Way, Kirkland, WA 98033', theme: 3, google_place_id: 'ChIJPULEDOcSkFQR1U-Kb693H-I'},
  {name: 'Bluebeard Coffee Roasters', location: '2201 6th Ave, Tacoma, WA 98403', theme: 3, google_place_id: 'ChIJN_TFiRpVkFQR34OKg46r6ao'},
  {name: 'Black Swan Coffee Roasting', location: '8510 Cedarhome Dr, Stanwood, WA 98292', theme: 3, google_place_id: 'ChIJh-cbC29chVQRBhk3M6MRoIw'},
  {name: 'Camano Island Coffee Roasters', location: '848 N Sunrise Blvd, Camano Island, WA 98282', theme: 3, google_place_id: 'ChIJS87SdVlehVQR86Jp2Lu3cNQ'},
  {name: 'RainShadow Coffee Roasting Company', location: '157 W Cedar St, Sequim, WA 98382', theme: 3, google_place_id: 'ChIJ3dQoOVq_j1QRkKHTZqxI6_k'},
  {name: 'Honeymoon Bay Coffee Roasters', location: '1100 SW Bowmer St A101, Oak Harbor, WA 98277', theme: 3, google_place_id: 'ChIJR1qr7j2Kj1QRjdaVuzPDGys'},
  {name: 'Red Door Coffee Roasters', location: '7425 Hardeson Rd, Everett, WA 98203', theme: 3, google_place_id: 'ChIJS1rYyh4BkFQR_Htxmm-_Dso'},
  {name: 'Majestic Mountain Coffee Roasters', location: '11229 NE State Hwy 104, Kingston, WA 98346', theme: 3, google_place_id: 'ChIJC45A8RMZkFQRJ3gK7mUR6V4'},
  {name: 'Broadcast Coffee Roasters', location: '1918 E Yesler Way, Seattle, WA 98122', theme: 3, google_place_id: 'ChIJnfADisFqkFQRu068u63UzZE'},
  {name: 'Stumptown Coffee Roasters', location: '1115 12th Ave, Seattle, WA 98122', theme: 3, google_place_id: 'ChIJ20f6lM5qkFQRRF904wHOvUw'},
  {name: 'Seven Coffee Roasters Market & Cafe', location: '2007 NE Ravenna Blvd, Seattle, WA 98105', theme: 3, google_place_id: 'ChIJicdX0XwUkFQR-XNas59i9_E'},
  {name: 'Zoka Coffee Roaster & Tea Company', location: '2200 N 56th St, Seattle, WA 98103', theme: 3, google_place_id: 'ChIJbwN2TEMUkFQR7UMDEHAT3aQ'},
  {name: 'True North Coffee Roasters', location: '1406 NW 53rd St, Seattle, WA 98107', theme: 3, google_place_id: 'ChIJP1kCxckVkFQR8o_h-uP2Azo'},
  {name: 'Ventoux Roasters and Hart Coffee', location: '3404 NE 55th St, Seattle, WA 98105', theme: 3, google_place_id: 'ChIJa86ZUIAUkFQRpZsW53nmORA'},
  {name: 'Seattle Coffee Works', location: '107 Pike St, Seattle, WA 98101', theme: 3, google_place_id: 'ChIJmx-U_7JqkFQRdymQucyLhXA'},
  {name: 'QED Coffee', location: '1418 31st Ave S, Seattle, WA 98144', theme: 3, google_place_id: 'ChIJJwQW3fNqkFQRMJoz9DoLCIo'},
  {name: 'Fonté Cafe & Wine Bar', location: '1321 1st Ave, Seattle, WA 98101', theme: 3, google_place_id: 'ChIJx_rKPrJqkFQR7OliFT0Jk-A'},
  {name: 'Caffe Vita', location: '5028 Wilson Ave S, Seattle, WA 98118', theme: 3, google_place_id: 'ChIJyXdUbBpqkFQRUmemX3gCia8'},
  {name: 'Tin Umbrella Coffee', location: '5600 Rainier Ave S, Seattle, WA 98118', theme: 3, google_place_id: 'ChIJTYqrswVqkFQRT4B_fot11UI'}
]

beer_biz_data = [
  {name: 'Holy Mountain Brewing Company', location: '1421 Elliott Ave W, Seattle, WA 98119', theme: 1, google_place_id: 'ChIJ5XSSCmUVkFQRtuGiC61S0OI'},
  {name: 'Standard Brewing', location: '2504 S Jackson St, Seattle, WA 98144', theme: 1, google_place_id: 'ChIJzTJUBulqkFQRFBINymBrPOw'},
  {name: 'Schooner Exact Brewing Company', location: '3901 1st Avenue South, Seattle, WA 98134', theme: 1, google_place_id: 'ChIJT_EoO81BkFQRZ_G742R5YNk'},
  {name: 'Two Beers Brewing Co.', location: '4700 Ohio Ave S, Seattle, WA 98134', theme: 1, google_place_id: 'ChIJj-Owz8lBkFQR4YGZWeGpBDE'},
  {name: 'Stoup Brewing', location: '1108 NW 52nd St, Seattle, WA 98107', theme: 1, google_place_id: 'ChIJj-Owz8lBkFQR4YGZWeGpBDE'},
  {name: 'Outlander Brewery and Pub', location: '225 N 36th St, Seattle, WA 98103', theme: 1, google_place_id: 'ChIJ1zVasKkVkFQRhqqfhqmOfEY'},
  {name: 'Big Time Brewery & Alehouse', location: '4133 University Way NE, Seattle, WA 98105', theme: 1, google_place_id: 'ChIJKaC2QvMUkFQRWVvn71SBmuY'},
  {name: 'Naked City Brewery & Taphouse', location: '8564 Greenwood Ave N, Seattle, WA 98103', theme: 1, google_place_id: 'ChIJacmILCAUkFQRdc6zDu0K4wM'},
  {name: 'Snoqualmie Brewery and Taproom', location: '8032 Falls Ave SE, Snoqualmie, WA 98065', theme: 1, google_place_id: 'ChIJK_wlUeZ7kFQRjxUNVTYixAY'},
  {name: 'Airways Brewing Company - Brewery & Tap Room', location: '8611 S 212th St, Kent, WA 98031', theme: 1, google_place_id: 'ChIJAcTKjYxckFQR0W0BMq-XvD4'},
  {name: 'Elliott Bay Brewhouse & Pub', location: '255 SW 152nd St, Burien, WA 98166', theme: 1, google_place_id: 'ChIJQypYVJxEkFQRMvgEtMsG2sE'},
  {name: 'Sound Brewery Tasting Room', location: '19815 Viking Ave NW, Poulsbo, WA 98370', theme: 1, google_place_id: 'ChIJNfm6RJojkFQRLDQNpmjxBec'},
  {name: 'Port Townsend Brewing Co', location: '330 10th St, Port Townsend, WA 98368', theme: 1, google_place_id: 'ChIJL9ElPTTsj1QRD93ylhrNMPM'},
  {name: 'Diamond Knot Brewery & Alehouse', location: '621 Front St, Mukilteo, WA 98275', theme: 1, google_place_id: 'ChIJf40oSpQBkFQRoDocr1VpJJs'},
  {name: 'Black Raven Brewing Company', location: '14679 NE 95th St, Redmond, WA 98052', theme: 1, google_place_id: 'ChIJ45n4RVoNkFQRgTGyL_s0wlQ'},
  {name: 'Elliott Bay Brewery', location: '12537 Lake City Way NE, Seattle, WA 98125', theme: 1, google_place_id: 'ChIJVVVVVUkQkFQR7O6mdrhQ6BI'},
  {name: 'Hi-Fi Brewing', location: '14950 NE 95th St, Redmond, WA 98052', theme: 1, google_place_id: 'ChIJFcdlvVoNkFQR3Sc7bapFaEY'},
  {name: 'Bushnell Craft Brewing Company', location: '8461 164th Ave NE, Redmond, WA 98052', theme: 1, google_place_id: 'ChIJl9FoGrNykFQRG6ug8HZ2Rwg'},
  {name: 'Mac & Jack\'s Brewery', location: '17825 NE 65th St, Redmond, WA 98052', theme: 1, google_place_id: 'ChIJN6Z_F5ZykFQRiO5d788ddlU'},
  {name: 'Chainline Brewing Company', location: '503 6th St S, Kirkland, WA 98033', theme: 1, google_place_id: 'ChIJTT3jSNsSkFQRGTbj9GYb5qM'},
  {name: 'Bellevue Brewing Company', location: '1820 130th Ave NE #2, Bellevue, WA 98005', theme: 1, google_place_id: 'ChIJ6VEtuP5skFQRmAqRGSLpnfQ'},
  {name: 'Geaux Brewing', location: '12031 Northup Way #203, Bellevue, WA 98005', theme: 1, google_place_id: 'ChIJt9K7FuVskFQR2jxXU5RDqAo'},
  {name: 'Resonate Brewery + Pizzeria', location: '5606 119th Ave SE, Bellevue, WA 98006', theme: 1, google_place_id: 'ChIJAS74WBVpkFQRVQoMkl6YcuA'},
  {name: 'Four Generals Brewing', location: '229 Wells Ave S, Renton, WA 98057', theme: 1, google_place_id: 'ChIJHQ2QF6tCkFQRMgx6qSEpELA'},
  {name: 'Herbert B. Friendly Brewing', location: '527 Wells Ave S, Renton, WA 98057', theme: 1, google_place_id: 'ChIJ-4E6olNdkFQR8GvgyhHLn-A'},
  {name: 'Odin Brewing Company', location: '402 Baker Blvd, Tukwila, WA 98188', theme: 1, google_place_id: 'ChIJScTGeNZckFQRmGWHEzxL38U'},
  {name: 'Big Al Brewing', location: '9832 14th Ave SW, Seattle, WA 98106', theme: 1, google_place_id: 'ChIJ-XXc191DkFQRYvJW1UnCDNg'},
  {name: 'Tin Dog Brewing', location: '309 S Cloverdale St Suite A2, Seattle, WA 98108', theme: 1, google_place_id: 'ChIJkUuO6ipCkFQR6LvgFLot3t8'},
  {name: 'Lowercase Brewing - Brewery', location: '8103 8th Ave S, Seattle, WA 98108', theme: 1, google_place_id: 'ChIJZXbvlodBkFQRY6tMrcfWk3U'},
  {name: 'Counterbalance Brewing Company', location: '503B S Michigan St, Seattle, WA 98108', theme: 1, google_place_id: 'ChIJo5hlPpRBkFQRN4n4eddhkKU'},
  {name: 'Elliott Bay Brewery & Pub', location: '4720 California Ave SW, Seattle, WA 98116', theme: 1, google_place_id: 'ChIJKdCRYvlAkFQR4o1cPE_IfQI'},
  {name: 'Machine House Brewery', location: '5840 Airport Way S #121, Seattle, WA 98108', theme: 1, google_place_id: 'ChIJJ_dUL-pBkFQRD3uY_y1errw'},
  {name: 'Spinnaker Bay Brewing', location: '5718 Rainier Ave S, Seattle, WA 98118', theme: 1, google_place_id: 'ChIJK-8_PwRqkFQRNdEqlgGJfCI'},
  {name: 'Flying Lion Brewing', location: '5041 Rainier Ave S, Seattle, WA 98118', theme: 1, google_place_id: 'ChIJkV5Uwg5qkFQRvKA7wyqgRP8'},
  {name: 'Georgetown Brewing Co', location: '5200 Denver Ave S, Seattle, WA 98108', theme: 1, google_place_id: 'ChIJcfLhScFBkFQRz55LZysPDzw'},
  {name: 'Optimism Brewing Company', location: '1158 Broadway, Seattle, WA 98122', theme: 1, google_place_id: 'ChIJiZvwB8xqkFQRNsl_0IBlxK4'},
  {name: 'Outer Planet Craft Brewing', location: '1812 12th Ave #100, Seattle, WA 98122', theme: 1, google_place_id: 'ChIJE18qpdJqkFQRkvLYZOAQf78'},
  {name: 'Cloudburst Brewing', location: '2116 Western Ave, Seattle, WA 98121', theme: 1, google_place_id: 'ChIJg-YsE00VkFQRavJQE7x8jLY'},
  {name: 'Old Stove Brewing', location: '1525 1st Ave #16, Seattle, WA 98101', theme: 1, google_place_id: 'ChIJy0xg5rJqkFQRBBJiQYHnQaI'},
  {name: 'McMenamins Six Arms', location: '300 E Pike St, Seattle, WA 98122', theme: 1, google_place_id: 'ChIJ2Rza3cpqkFQRZdmDkG51JUc'},
  {name: 'Urban Family Brewing Co.', location: '4441 26th Ave W, Seattle, WA 98199', theme: 1, google_place_id: 'ChIJv7O2W8YVkFQRXrzXrlftG3Q'},
  {name: 'Fremont Brewing Company', location: '1050 N 34th St, Seattle, WA 98103', theme: 1, google_place_id: 'ChIJ75GmYwEVkFQR8zzS82BwLVQ'},
  {name: 'Outlander Brewery and Pub', location: '225 N 36th St, Seattle, WA 98103', theme: 1, google_place_id: 'ChIJ1zVasKkVkFQRhqqfhqmOfEY'},
  {name: 'Hale\'s Ales Brewery & Pub', location: '4301 Leary Way NW, Seattle, WA 98107', theme: 1, google_place_id: 'ChIJ13C0MrAVkFQRwzOcYlDXSFo'},
  {name: 'Rooftop Brewing Company', location: '1220 W Nickerson St, Seattle, WA 98119', theme: 1, google_place_id: 'ChIJ88tzCQgVkFQRgIpSPGSf9KI'},
  {name: 'Peddler Brewing Company', location: '1514 NW Leary Way, Seattle, WA 98107', theme: 1, google_place_id: 'ChIJ2U9kI7gVkFQRxkJg9lPKA8A'},
  {name: 'NW Peaks Brewery', location: '4818 17th Ave NW, Seattle, WA 98107', theme: 1, google_place_id: 'ChIJGQ3ylCMUkFQRU05M6fuCKK4'},
  {name: 'Bad Jimmy\'s Brewing Co.', location: 'B, 4358 Leary Way NW, Seattle, WA 98107', theme: 1, google_place_id: 'ChIJYRX7r7EVkFQRDsrh3U9e0Qw'},
  {name: 'Populuxe Brewing', location: '826B NW 49th St, Seattle, WA 98107', theme: 1, google_place_id: 'ChIJQc9bn7YVkFQRh4Me6O1725E'},
  {name: 'Reuben\'s Brews', location: '5010 14th Ave NW, Seattle, WA 98107', theme: 1, google_place_id: 'ChIJP1kCxckVkFQRq_Hc5aXF15A'},
  {name: 'Cedar River Brewing Company', location: '7410 Greenwood Ave N #B, Seattle, WA 98103', theme: 1, google_place_id: 'ChIJU6f8NzsUkFQRJxa6p_w9ww4'},
  {name: 'Flying Bike Cooperative Brewery', location: '8570 Greenwood Ave N, Seattle, WA 98103', theme: 1, google_place_id: 'ChIJzwr1KSAUkFQRUmCNDSvzmpA'},
  {name: 'Ravenna Brewing Co', location: '5408 26th Ave NE, Seattle, WA 98105', theme: 1, google_place_id: 'ChIJCd7LiX0UkFQR7BNDEJV8W7A'},
  {name: 'Floating Bridge Brewing', location: '722 NE 45th St, Seattle, WA 98105', theme: 1, google_place_id: 'ChIJOd9XfPUUkFQRbeyZVOO3S6U'},
  {name: 'Hellbent Brewing Company', location: '13035 Lake City Way NE, Seattle, WA 98125', theme: 1, google_place_id: 'ChIJeVKwbHoRkFQR17m_DCgxrGc'},
  {name: 'Lantern Brewing', location: '938 N 95th St, Seattle, WA 98103', theme: 1, google_place_id: 'ChIJI0KS8qcWkFQR5tYUfNqyXoU'},
  {name: '192 Brewing Company', location: '7324 NE 175th St, Kenmore, WA 98028', theme: 1, google_place_id: 'ChIJNxbsscoPkFQReMtkN3NsQ5A'},
  {name: 'Sumerian Brewing Company', location: '15510 Woodinville-Redmond Rd NE E110, Woodinville, WA 98072', theme: 1, google_place_id: 'ChIJUa63dMsNkFQRhxFScKYWOMQ'},
  {name: 'Redhook Brewery Woodinville', location: '14300 NE 145th St, Woodinville, WA 98072', theme: 1, google_place_id: 'ChIJIVwNtrUNkFQREteqCs7sxZI'},
  {name: 'Dirty Bucket Brewing Co.', location: '19151 144th Ave NE, Woodinville, WA 98072', theme: 1, google_place_id: 'ChIJuUipwpgOkFQRSYTSJZxxW3c'},
  {name: 'Fish Brewing', location: '14701 148th Ave NE, Woodinville, WA 98072', theme: 1, google_place_id: 'ChIJVTlurbQNkFQRaS4RplOrMvM'},
  {name: 'Triplehorn Brewing Co', location: '19510 144th Ave NE #6, Woodinville, WA 98072', theme: 1, google_place_id: 'ChIJjRse7qIOkFQRoK7dYJ93ziE'},
  {name: 'Diamond Knot Brewpub @ MLT', location: '5602 232nd St SW, Mountlake Terrace, WA 98043', theme: 1, google_place_id: 'ChIJ62Ompw8QkFQRnJdQbl3eJ5M'},
  {name: 'American Brewing Company Inc.', location: '180 W Dayton St, Edmonds, WA 98020', theme: 1, google_place_id: 'ChIJbzFcjfgakFQRohSDp395h18'},
  {name: 'Big E Ales', location: '5030 208th St SW, Lynnwood, WA 98036', theme: 1, google_place_id: 'ChIJD1k23lEFkFQRGEYgyvfiZEY'},
  {name: 'Salish Sea Brewing Co.', location: '518 Dayton St #104, Edmonds, WA 98020', theme: 1, google_place_id: 'ChIJB2qcaPoakFQRxj3N6ABHxqo'}
]

distillery_biz_data = [
  {name: 'Westland Distillery', location: '2931 1st Avenue South Seattle, WA 98134', theme: 2, google_place_id: 'ChIJ8WRf7i5AkFQRfe6bKjobuOg'},
  {name: '2Bar Spirits', location: '2960 4th Ave S #106 Seattle, WA 98134', theme: 2, google_place_id: 'ChIJNWq06CtAkFQR_ugKDtLthoE'},
  {name: '3 Howls Distillery', location: '426 S Massachusetts St Seattle, WA 98134', theme: 2, google_place_id: 'ChIJ73F1sp5qkFQRlbX0loXiMzg'},
  {name: 'Letterpress Distilling', location: '85 S Atlantic St #110 Seattle, WA 98134', theme: 2, google_place_id: 'ChIJX4sXkJ9qkFQRKfz2s6irpQg'},
  {name: 'Copperworks Tasting Room & Distillery', location: '1250 Alaskan Way Seattle, WA 98101', theme: 2, google_place_id: 'ChIJHS40Aq5qkFQRlleEHKegkHk'},
  {name: 'OOLA Distillery', location: '1314 E Union St Seattle, WA 98122', theme: 2, google_place_id: 'ChIJ_7lmbs5qkFQR_JtyDWDCBy4'},
  {name: 'Sun Liquor Distillery', location: '514 E Pike St Seattle, WA 98122', theme: 2, google_place_id: 'ChIJa4OcDctqkFQRuo1Lzs_GSIA'},
  {name: 'Batch 206', location: '1417 Elliott Ave W Seattle, WA 98119', theme: 2, google_place_id: 'ChIJE0oRnmUVkFQRbZ_Akr9BMJ8'},
  {name: 'Sound Spirits', location: '1630 15th Ave W Seattle, WA 98119', theme: 2, google_place_id: 'ChIJU2Fvc3AVkFQROI89yejoFGA'},
  {name: 'Old Ballard Liquor Co.', location: '4421 Shilshole Ave NW Seattle, WA 98107', theme: 2, google_place_id: 'ChIJDxOK9rkVkFQR19WWaeHZzvs'},
  {name: 'Captive Spirits', location: '1518 NW 52nd St Seattle, WA 98107', theme: 2, google_place_id: 'ChIJyceNFcgVkFQRrZuw0dBbr7Q'},
  {name: 'Woodinville Whiskey Co.', location: '16110 Woodinville Redmond Rd NE Woodinville, WA 98072', theme: 2, google_place_id: 'ChIJMQvnftINkFQRYTX0aZwvCWA'},
  {name: 'JP Trodden Distilling', location: '18646 142nd Ave NE Woodinville, WA 98072', theme: 2, google_place_id: 'ChIJf2l5IZwOkFQRKf4afEpHIyQ'},
  {name: 'Pacific Distillery', location: '18808 142nd Ave NE #4B Woodinville, WA 98072', theme: 2, google_place_id: 'ChIJoeWGrZ4OkFQR4wzVgHCMsIU'},
  {name: 'Wildwood Spirits & Co.', location: '19116 Beardslee Blvd Ste 102 Bothell, WA 98011', theme: 2, google_place_id: 'ChIJsczvxmAOkFQRtUEHawfEW6o'},
  {name: 'Parliament Distillery', location: '14209 29th St E, Sumner, WA 98390', theme: 2, google_place_id: 'ChIJR8Lt-rz5kFQRIB_h1MZiMTM'},
  {name: 'Scratch Distillery', location: '190 Sunset Ave, Edmonds, WA 98020', theme: 2, google_place_id: 'ChIJCQfePfkakFQRL-LtWYFjttw'},
  {name: 'The Barrel Thief', location: '3417 Evanston Ave N #102, Seattle, WA 98103', theme: 2, google_place_id: 'ChIJpVLqQQcVkFQRZEsgerL_wUY'},
  {name: 'Bad Dog Distillery', location: '19109 63rd Ave NE Suite 1A, Arlington, WA 98223', theme: 2, google_place_id: 'ChIJEfPBEdpPhVQRye0ue35R1R4'},
  {name: 'BelleWood Distilling', location: '6140 Guide Meridian #3, Lynden, WA 98264', theme: 2, google_place_id: 'ChIJ6SnY1k-6hVQR2F_anea3bOg'},
  {name: 'Blackfish Spirits Distillery', location: '420 37th St NW, Auburn, WA 98001', theme: 2, google_place_id: 'ChIJD8T9agJZkFQRDX-u5qoIxyg'},
  {name: 'Black Heron Spirits', location: '8011 Keene Rd, West Richland, WA 99353', theme: 2, google_place_id: 'ChIJw_bACbZvmFQR3_BNxXJeKG0'},
  {name: 'BroVo Spirits', location: '18808 142nd Ave NE, Woodinville, WA 98072', theme: 2, google_place_id: 'ChIJXQbZrZ4OkFQR_rnx5bU87Gw'},
  {name: 'Cadée Distillery', location: '8912 WA-525, Clinton, WA 98236', theme: 2, google_place_id: 'ChIJv0XJrRL-j1QRgJslph-nVq0'},
  {name: 'Chambers Bay Distillery', location: '2013 70th Ave W, University Place, WA 98466', theme: 2, google_place_id: 'ChIJbxdBt96qkVQR9ztwThIzgbE'},
  {name: 'Chuckanut Bay Distillery', location: ' 1115 Railroad Avenue, Bellingham, WA 98225', theme: 2, google_place_id: 'ChIJU45k4bujhVQRypUoDoYCnMk'},
  {name: 'Four Leaf Spirits', location: '12280 NE Woodinville Dr, Woodinville, WA 98072', theme: 2, google_place_id: 'ChIJye67Yn4OkFQRmMZImFH9gJE'},
  {name: 'Fremont Mischief', location: '132 N Canal St, Seattle, WA 98103', theme: 2, google_place_id: 'ChIJVVVVVVEUkFQRK8JO0A8nJ2A'},
  {name: 'Heritage Distilling Company', location: '3207 57th St Ct NW, Gig Harbor, WA 98335', theme: 2, google_place_id: 'ChIJG7H-dSxTkFQRjOmtF9GVKeI'},
  {name: 'Salish Sea Organic Liqueurs', location: '2641 Willamette Dr NE Ste D Lacey, WA 98516', theme: 2, google_place_id: 'ChIJB2qcaPoakFQRxj3N6ABHxqo'},
  {name: 'Sandstone Distillery', location: '842 Wright Rd SE, Tenino, WA 98589', theme: 2, google_place_id: 'ChIJTWVvupxvkVQR-zPb0jxl2Lg'},
  {name: 'Seattle Distilling', location: '19429 Vashon Hwy SW, Vashon, WA 98070', theme: 2, google_place_id: 'ChIJEQWNcJBPkFQRIaBu6NCOMdg'},
  {name: 'Sidetrack Distillery', location: 'Lazy River Farm 27010 78th Ave S Kent, WA 98032', theme: 2, google_place_id: 'ChIJaa0-_T9ZkFQRYbwsshxeiJo'},
  {name: 'Skip Rock Distillers', location: '104 Ave C, Snohomish, WA 98290', theme: 2, google_place_id: 'ChIJkc68w7WpmlQRyySOGFIobL4'},
  {name: 'Temple Distilling Company', location: '19231 36th Ave W, Lynnwood, WA 98036', theme: 2, google_place_id: 'ChIJG5ndR2wFkFQRHINu6nrXLeA'},
  {name: 'Valley Shine Distillery', location: '320 S 1st St, Mt Vernon, WA 98273', theme: 2, google_place_id: 'ChIJ38hTl-pshVQRvLpbU8EAH64'},
  {name: 'Whidbey Island Distillery', location: '3466 Craw Rd, Langley, WA 98260', theme: 2, google_place_id: 'ChIJheVoWDz8j1QR5STDHfGlWPA'},
  {name: 'Whiskey Gap Distillery', location: '213 W Main Ave, Ritzville, WA 99169', theme: 2, google_place_id: 'ChIJ2c6opYDenlQRrpttZHKX3X8'},
  {name: 'Wildwood Spirits Co.', location: '19116 Beardslee Blvd #102, Bothell, WA 98011', theme: 2, google_place_id: 'ChIJsczvxmAOkFQRtUEHawfEW6o'},
  {name: 'Wishkah River Distillery', location: '2210 Port Industrial Rd, Aberdeen, WA 98520', theme: 2, google_place_id: 'ChIJrfQ8Zuw5klQRZqgU5heZBdo'},
  {name: 'SoDo Spirits Distillery', location: '2228 Occidental Ave S Seattle, WA 98134', theme: 2, google_place_id: 'ChIJgTNUuydAkFQRuzWq0nHXWec'},
  {name: 'Bainbridge Organic Distillers', location: '9727 Coppertop Loop NE Bainbridge Island, WA 98110', theme: 2, google_place_id: 'ChIJ7yXoXiI8kFQRFaQyVPhK8WU'},
  {name: 'Tucker Distillery', location: '5451 NW Newbery Hill Rd Silverdale, WA 98383', theme: 2, google_place_id: 'ChIJgQbFN24wkFQRG5HEvMQ5Asw'},
  {name: 'Headframe Spirits', location: '21 S Montana St, Butte, MT 59701', theme: 2, google_place_id: 'ChIJH4PiB7UJW1MR4prCmNotAZ8'},
  {name: 'Spiritopia Liqueurs', location: '720 NE Granger Ave, Corvallis, OR 97330', theme: 2, google_place_id: 'ChIJEUTgYnsVwFQRBp1_LSq3Ag8'},
  {name: 'Martin Ryan Distilling Co', location: '2304 NW Savier St, Portland, OR 97210', theme: 2, google_place_id: 'ChIJIzQSseUJlVQRXfrvr1WSvk8'}
]

distillery_biz_data.each do |business_data|
  Business.find_or_create_by(business_data)
end

beer_biz_data.each do |business_data|
  Business.find_or_create_by(business_data)
end

coffee_biz_data.each do |business_data|
  Business.find_or_create_by(business_data)
end

wine_biz_data.each do |business_data|
  Business.find_or_create_by(business_data)
end
